name: Upstream Synchronization

on:
  schedule:
    - cron: '0 8 * * *'  # Daily at 08:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cherrygram-support from Fork (Full History)
        uses: actions/checkout@v4
        with:
          ref: cherrygram-support
          fetch-depth: 0

      - name: Configure Git Identity
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Checkout Main Branch
        run: git checkout main

      - name: Verify & Configure Upstream Remote
        run: |
          git remote add upstream https://github.com/Sakion-Team/Re-Telegram.git || echo "Upstream remote already configured"

      - name: Fetch Upstream Repository Updates
        run: git fetch upstream

      - name: Hard Reset Main to Upstream/Main (Exact Mirror)
        run: |
          git reset --hard upstream/main
          git clean -fd

      - name: Force Push Updated Main to Origin
        run: git push --force origin main
